version: "3.8"

services:
  frontend:
    build:
      context: ./marketplace-frontend
    ports:
      - "8080:80" 
    environment:
      VUE_APP_API_ENDPOINT: http://backend:3000 
    depends_on:
      - backend 

  backend:
    build:
      context: ./marketplace-backend
    ports:
      - "3000:3000" 
    environment:
      MONGODB_URI: mongodb://mongodb:27017/MarketPlace 
    depends_on:
      - mongodb 

  mongodb:
    image: mongo:6.0 
    container_name: mongodb-container 
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 

volumes:
  mongodb_data: 
